version: "3"

services:
  jupyterlab:
    build: ./jupyterlab

    ports:
      - 3001:8888
    volumes:
      - lab_home:/home/jovyan
      - notebooks:/work

    command:
      - --NotebookApp.password="${PASSWORD}" --NotebookApp.notebook_dir=/work

    env_file: .env

    restart: always

  db:
    image: mariadb

    volumes:
      - db:/var/lib/mysql

    env_file: .env

    restart: always

  nextcloud:
    build: ./nextcloud

    depends_on:
      - db

    ports:
      - 3002:80
    volumes:
      - notebooks:/notebooks
      - nextcloud:/var/www/html

    environment:
      - MYSQL_HOST=db
    env_file: .env

    restart: always

volumes:
  db:
  lab_home:
  nextcloud:
  notebooks:
