version: "3"

services:
  jupyterlab:
    build: ./jupyterlab

    ports:
      - 3001:8888
    volumes:
      - files:/work

    command:
      - --NotebookApp.password="${PASSWORD}" --NotebookApp.notebook_dir=/work

    env_file: .env

    restart: always

  db:
    image: mariadb

    volumes:
      - db:/var/lib/mysql

    env_file: .env

    restart: always

  filerun:
    build: ./filerun

    depends_on:
      - db

    ports:
      - 3002:80
    volumes:
      - files:/user-files

    environment:
      - FR_DB_HOST=db
      - FR_DB_PORT=3306
      - APACHE_RUN_USER=filerun
      - APACHE_RUN_GROUP=filerun
    env_file: .env

    restart: always

volumes:
  files:
  db:
